import Navbar from "@/components/navbar";
import {
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider
} from '@clerk/nextjs';
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import "./globals.css";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}>
      <html lang="en">
        <body>
          <ClerkLoading>
            <div className=" flex items-center justify-center h-screen text-7xl font-bold">
               Loading....
            </div>
          </ClerkLoading>
          <ClerkLoaded>
          <div className="max-w-6xl mx-auto">
            <div className="flex flex-col h-screen">
              <Navbar/>
              {children}
            </div>
          </div>
          </ClerkLoaded>
         
        </body>
      </html>
    </ClerkProvider>
  )
}
